function [Prepair, Stimuli] = config(group, subNo)
%------------------------------------------
% SCRIPT HEADER
%------------------------------------------
try
	%--------------------- 
	% Setup variables
	%--------------------- 
	format long; % set output format
	% Folders
	f1 = 'inFolder';     v1 = 'input/';  	        % input folder
	f2 = 'outFolder';    v2 = strcat('output/', group, '_', num2str(subNo), '/');    % output folder
	f3 = 'soundFolder';  v3 = 'stimuli/sounds/';    % sound folder
	f4 = 'imgFolder';    v4 = 'stimuli/images/';    % image folder
	f5 = 'textFolder';   v5 = 'stimuli/text/';

	% screen and response 
	f6 = 'skipTest';     v6 = 0; 				    % 0 = skip test, 1 = do not skip test
	f7 = 'textSize';     v7 = 26; 				    % default text size
	f8 = 'keyArray';     v8 = {{'b'}};              % response and pause keys
	f9 = 'timeoutDur';   v9 = 2.0;				    % maximum time allowed to respond on each trial

	% data files
	f10 = 'exptName';    v10 = group;  			    % base name of all output files
	f11 = 'nOutfile';    v11 = 1; 				    % number of output files to be opened
	f12 = 'isLogfile';   v12 = 1; 				    % 1 signals to create a log file
	f13 = 'tableVariable'; v13 = {{'group', ...     % variable names to print to outfile
	                               'subNo', ...
	                               'block', ...     
								   'index', ...
								   'seqDur', ...
								   'shortLong', ...
								   'nTargets', ...
								   'nIOI', ...				 
								   'rhythmicVarTAG', ... 
								   'seqSTD', ...
								   'seqMeanIOI', ...
								   'seqSumIOI', ...
								   'Lowbound', ...
								   'Upbound', ...  
								   'pressedKey', ...
								   'rt', ...
								   'seqDuration', ...
								   'startInterval', ...
								   'trialDuration', ...
								   'IOI1', 'IOI2', 'IOI3', 'IOI4', 'IOI5', 'IOI6', ...
								   'IOI7', 'IOI8', 'IOI9'}};

	f14 = 'textFile'; v14 = 'instructions'; 

	Prepair = struct(f1, v1, f2,  v2,  f3,  v3, f4, v4, ...
					 f5, v5, f6,  v6,  f7,  v7, f8, v8, ...
					 f9, v9, f10, v10, f11, v11, f12, v12, ...
					 f13, v13, f14, v14);

    %--------------------- 
	% Stimulus variables
	%--------------------- 
	f1 = 'noiseDur';        v1 = 0.040;    % duration of noise
	f2 = 'isRamp';		    v2 = 1;	       % include on-off set ramps when generating noise 1 = include	
	f3 = 'gateDur';	  	    v3 = 0.005;	   % duration of on and offset cosin ramps	
	f4 = 'playbackFreq';    v4 = 48828;    % sampling rate of sound files
	f5 = 'periodicIOI';     v5 = 0.250;    % default interonset interval on periodic trials
	
	Stimuli = struct(f1, v1, f2, v2, f3, v3, f4, v4, ...
					 f5, v5);
	
	%---------------------
catch ME
    rethrow(ME);
end
%------------------------------------------